# Generated by Django 4.1.6 on 2023-02-12 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='عنوان دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی  ها',
            },
        ),
        migrations.CreateModel(
            name='Protfillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='عنوان نمونه کار')),
                ('image', models.ImageField(upload_to='images/portfiilo/images/', verbose_name='تصویر نمونه کار')),
                ('video', models.FileField(blank=True, null=True, upload_to='images/portfiilo/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.mp4'], message='نوع فایل نادرست  لطفا یک ویدیو انتخاب کنید ! ')], verbose_name='ویدیو از نمونه کار درصورت داشتن')),
                ('category', models.ManyToManyField(to='Protfillo.category', verbose_name='دسته بندی نمونه کار')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کار ها',
            },
        ),
    ]
