# Generated by Django 4.1.6 on 2023-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protfillo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protfillo',
            name='video',
        ),
        migrations.AddField(
            model_name='protfillo',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to='images/portfiilo/image_link/', verbose_name='عکس پیشنمایش پروژه در صورت داشتن'),
        ),
    ]
