# Generated by Django 4.1.6 on 2023-02-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Protfillo', '0002_remove_protfillo_video_protfillo_image_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Protfillo',
            new_name='Portfillo',
        ),
    ]
