# Generated by Django 4.1.6 on 2023-02-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protfillo', '0003_rename_protfillo_portfillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfillo',
            name='category',
            field=models.ManyToManyField(related_name='c_portfillo', to='Protfillo.category', verbose_name='دسته بندی نمونه کار'),
        ),
    ]
