# Generated by Django 4.1.6 on 2023-02-23 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocontact',
            name='phone',
            field=models.CharField(max_length=110, validators=[django.core.validators.RegexValidator('09([0-9][0-9]|3[1-9]|2[1-9])-?[0-9]{3}-?[0-9]{4}', message='لطفا شناره تلفن صحیح وارد کنید شماره تلفن شما اشتباه است دوست من ')], verbose_name='شماره تماس'),
        ),
    ]
