# Generated by Django 4.1.6 on 2023-02-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='نام ')),
                ('lived_in', models.CharField(max_length=50, verbose_name='محل زندگی ')),
                ('biography', models.TextField(verbose_name='بیوگرافی در مورد خود')),
                ('total_projects', models.IntegerField(default=0, verbose_name='پروژه های موفق')),
                ('experince', models.IntegerField(default=0, verbose_name='تجربه کار بر اساس سال')),
            ],
            options={
                'verbose_name': 'بیوگرافی',
                'verbose_name_plural': 'بیوگرافی ها',
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-persent']},
        ),
        migrations.AlterField(
            model_name='skill',
            name='persent',
            field=models.IntegerField(default=0, verbose_name='درصد تسلط'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=110, verbose_name='عنوان مهارت'),
        ),
    ]
