# Generated by Django 4.1.6 on 2023-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_biography_alter_skill_options_alter_skill_persent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='عنوان علاقه مندی شما')),
                ('icon', models.CharField(choices=[('fas fa-music', 'آیکون موزیک'), ('fas fa-route', 'آیکون گردشگری'), ('fas fa-image', 'آیکون تصاویر'), ('fas fa-film', 'آیکون فیلم'), ('fas fa-space-shuttle', 'آیکون سفینه فضایی'), ('fas fa-book', 'آیکون کتاب'), ('fas fa-gamepad', 'آیکون بازی'), ('fas fa-tree', 'آیکون درخت')], max_length=40, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'علاقه',
                'verbose_name_plural': 'علایق',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='عنوان خدمات')),
                ('description', models.TextField(verbose_name='توضیحات خدمات')),
                ('icon', models.CharField(choices=[('fas fa-cogs', 'آیکون چرخ دنده'), ('fas fa-desktop', 'آیکون دسکتاپ'), ('fas fa-mobile-alt', 'آیکون موبایل'), ('fas fa-medkit', 'آیکون جعبه کمک اولیه')], max_length=30, verbose_name='آیکون برای خدمت مورد نظر')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-persent'], 'verbose_name': 'مهارت ', 'verbose_name_plural': 'مهارت ها'},
        ),
    ]
