# Generated by Django 4.1.6 on 2023-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_educational_workexperince'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educational',
            options={'verbose_name': 'سابقه تحصیلی', 'verbose_name_plural': 'سوابق تحصیلی'},
        ),
        migrations.AddField(
            model_name='biography',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='biography/avatar/', verbose_name='اواتار'),
        ),
    ]
